---

name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install Debian Packages
        run: |
          sudo apt update
          sudo apt install -y cmake libxkbcommon-dev libegl1-mesa-dev \
            libglib2.0-dev libgirepository1.0-dev ninja-build
      - name: Setup Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.6
      - name: Python Package Cache
        uses: actions/cache@v1
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('.github/workflows/ci.yml') }}
          restore-keys: ${{ runner.os }}-pip-
      - name: Install Python Packages
        run: |
          pip install --upgrade pip gi-docgen==2021.2 meson==0.49
          printf '#! /bin/sh\nexec python -m gidocgen.gidocmain "$@"\n' \
            > "$(which gi-docgen)"
      - name: Meson - Configure
        run: |
          mkdir -p _work/meson
          meson _work/meson/build --prefix /usr -Dbuild-docs=true
      - name: Meson - Build
        run: |
          ninja -C _work/meson/build
      - name: Meson - Install
        run: |
          DESTDIR="$(pwd)/_work/meson/prefix" ninja -C _work/meson/build install
          nm -D -P _work/meson/build/libwpe-1.0.so \
            | awk '$2 == "T" || $2 == "U" {print $2 " " $1}' \
            > _work/meson/symbols
          (cd _work/meson/prefix && find lib -type f | sort) > _work/meson/files
      - name: Meson - Archive Artifacts
        uses: actions/upload-artifact@v1
        with:
          name: build-meson
          path: _work/meson/prefix
      - name: Meson - Archive Documentation
        uses: actions/upload-artifact@v2
        with:
          name: docs
          path: _work/meson/build/docs
      - name: CMake - Configure
        run: |
          mkdir -p _work/cmake/build && cd $_
          cmake -DCMAKE_INSTALL_PREFIX=/usr -DBUILD_DOCS=OFF ../../..
      - name: CMake - Build
        run: |
          make -C _work/cmake/build -j$(nproc)
      - name: CMake - Install
        run: |
          DESTDIR="$(pwd)/_work/cmake/prefix" make -C _work/cmake/build install
          nm -D -P _work/cmake/build/libwpe-1.0.so \
            | awk '$2 == "T" || $2 == "U" {print $2 " " $1}' \
            > _work/cmake/symbols
          (cd _work/cmake/prefix && find lib -type f | sort) > _work/cmake/files
      - name: CMake - Archive Artifacts
        uses: actions/upload-artifact@v1
        with:
          name: build-cmake
          path: _work/cmake/prefix
      - name: Check Installations
        run: |
          diff -u _work/{cmake,meson}/files
          diff -u _work/{cmake,meson}/symbols
          diff -Naur _work/{cmake,meson}/prefix/usr/include/
  publish:
    if: ${{ github.ref == 'refs/heads/aperezdc/docs' }}
    needs: build
    runs-on: ubuntu-20.04
    steps:
      - name: Fetch Documentation
        uses: actions/download-artifact@v2
        with:
          name: docs
          path: html
      - name: Deploy Documentation
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: html
