---

name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install Debian Packages
        run: |
          sudo apt update
          sudo apt install -y flex libjson-glib-dev libxkbcommon-dev \
            libegl1-mesa-dev libxml2-dev libxslt1-dev libyaml-dev llvm-dev \
            libclang-dev libglib2.0-dev ninja-build
      - name: Setup Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.6
      - name: Python Package Cache
        uses: actions/cache@v1
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('.github/workflows/ci.yml') }}
          restore-keys: ${{ runner.os }}-pip-
      - name: Install Python Packages
        run: |
          python -m pip install --upgrade pip setuptools wheel
          HOTDOC_BUILD_C_EXTENSION=enabled pip install hotdoc meson
      - name: Configure
        run: mkdir -p _work && meson _work/build --prefix /usr -Dbuild-docs=true
      - name: Build
        run: ninja -C _work/build
      - name: Install
        run: DESTDIR="$(pwd)/_work/files" ninja -C _work/build install
      - name: Archive Artifacts
        uses: actions/upload-artifact@v1
        with:
          name: build
          path: _work
